import * as fs from 'fs';
import * as path from 'path';
import { ScanResult } from './snyk';
import { logger } from '../../utils/logger';

export class HtmlReportGenerator {
    private outputDir: string;

    constructor() {
        this.outputDir = path.resolve(process.cwd(), 'scan-results');
        if (!fs.existsSync(this.outputDir)) {
            fs.mkdirSync(this.outputDir, { recursive: true });
        }
    }

    generate(result: ScanResult): string {
        const html = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Warden Security Report</title>
    <style>
        :root {
            --bg-color: #0f172a;
            --text-color: #f8fafc;
            --card-bg: #1e293b;
            --border-color: #334155;
            --critical: #ef4444;
            --high: #f97316;
            --medium: #eab308;
            --low: #3b82f6;
            --success: #22c55e;
        }
        body {
            font-family: 'Inter', system-ui, -apple-system, sans-serif;
            background-color: var(--bg-color);
            color: var(--text-color);
            margin: 0;
            padding: 2rem;
            line-height: 1.5;
        }
        .container {
            max-width: 1200px;
            margin: 0 auto;
        }
        header {
            margin-bottom: 2rem;
            border-bottom: 1px solid var(--border-color);
            padding-bottom: 1rem;
        }
        h1 { margin: 0; font-size: 2rem; }
        .meta { color: #94a3b8; font-size: 0.9rem; margin-top: 0.5rem; }
        
        .dashboard {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 1rem;
            margin-bottom: 2rem;
        }
        .card {
            background: var(--card-bg);
            padding: 1.5rem;
            border-radius: 0.5rem;
            border: 1px solid var(--border-color);
            text-align: center;
        }
        .count { font-size: 2.5rem; font-weight: bold; }
        .label { color: #94a3b8; font-size: 0.9rem; text-transform: uppercase; letter-spacing: 0.05em; }
        
        .text-critical { color: var(--critical); }
        .text-high { color: var(--high); }
        .text-medium { color: var(--medium); }
        .text-low { color: var(--low); }
        
        .vulnerabilities {
            display: flex;
            flex-direction: column;
            gap: 1rem;
        }
        .vuln-card {
            background: var(--card-bg);
            border-left: 4px solid var(--border-color);
            padding: 1.5rem;
            border-radius: 0 0.5rem 0.5rem 0;
            display: grid;
            gap: 0.5rem;
        }
        .vuln-card.critical { border-left-color: var(--critical); }
        .vuln-card.high { border-left-color: var(--high); }
        .vuln-card.medium { border-left-color: var(--medium); }
        .vuln-card.low { border-left-color: var(--low); }
        
        .vuln-header {
            display: flex;
            justify-content: space-between;
            align-items: flex-start;
        }
        .vuln-title { font-weight: bold; font-size: 1.1rem; }
        .badge {
            padding: 0.25rem 0.75rem;
            border-radius: 9999px;
            font-size: 0.75rem;
            font-weight: bold;
            text-transform: uppercase;
        }
        .badge.critical { background: rgba(239, 68, 68, 0.2); color: var(--critical); }
        .badge.high { background: rgba(249, 115, 22, 0.2); color: var(--high); }
        .badge.medium { background: rgba(234, 179, 8, 0.2); color: var(--medium); }
        .badge.low { background: rgba(59, 130, 246, 0.2); color: var(--low); }
        
        .vuln-details {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 1rem;
            font-size: 0.9rem;
            color: #cbd5e1;
            background: rgba(0,0,0,0.2);
            padding: 1rem;
            border-radius: 0.25rem;
        }
        .detail-item strong { display: block; color: #94a3b8; font-size: 0.8rem; margin-bottom: 0.25rem; }
        
        .no-issues {
            text-align: center;
            padding: 4rem;
            color: var(--success);
            font-size: 1.2rem;
        }
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>🛡️ Warden Scan Report</h1>
            <div class="meta">Generated by Warden on ${new Date(result.timestamp).toLocaleString()}</div>
        </header>

        <div class="dashboard">
            <div class="card">
                <div class="count">${result.summary.total}</div>
                <div class="label">Total Issues</div>
            </div>
            <div class="card">
                <div class="count text-critical">${result.summary.critical}</div>
                <div class="label">Critical</div>
            </div>
            <div class="card">
                <div class="count text-high">${result.summary.high}</div>
                <div class="label">High</div>
            </div>
            <div class="card">
                <div class="count text-medium">${result.summary.medium}</div>
                <div class="label">Medium</div>
            </div>
            <div class="card">
                <div class="count text-low">${result.summary.low}</div>
                <div class="label">Low</div>
            </div>
        </div>

        <section class="vulnerabilities">
            ${
                result.vulnerabilities.length === 0
                    ? `
                <div class="no-issues">
                    ✅ No vulnerabilities found. Your code is clean!
                </div>
            `
                    : result.vulnerabilities
                          .map(
                              (v) => `
                <div class="vuln-card ${v.severity}">
                    <div class="vuln-header">
                        <div class="vuln-title">${v.title}</div>
                        <span class="badge ${v.severity}">${v.severity}</span>
                    </div>
                    <div class="vuln-details">
                        <div class="detail-item">
                            <strong>PACKAGE</strong>
                            ${v.packageName}
                        </div>
                        <div class="detail-item">
                            <strong>VERSION</strong>
                            ${v.version}
                        </div>
                        <div class="detail-item">
                            <strong>ID</strong>
                            ${v.id}
                        </div>
                        <div class="detail-item">
                            <strong>FIXED IN</strong>
                            ${v.fixedIn && v.fixedIn.length ? v.fixedIn.join(', ') : 'No fix available'}
                        </div>
                    </div>
                </div>
            `
                          )
                          .join('')
            }
        </section>
    </div>
</body>
</html>
        `;

        const filepath = path.join(this.outputDir, 'scan-results.html');
        fs.writeFileSync(filepath, html);
        logger.success(`HTML Report generated: ${filepath}`);
        return filepath;
    }
}
